// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK2lUVoahQ0gOVVE4-m_FfoRJDZDw7Ey8',
    appId: '1:674981416486:web:2a19a558f044e80c44a0e7',
    messagingSenderId: '674981416486',
    projectId: 'user-list-win',
    authDomain: 'user-list-win.firebaseapp.com',
    storageBucket: 'user-list-win.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjDuwIbp7Dr_vwcwqPNAh_4XXNRQ0bb2I',
    appId: '1:674981416486:android:7e1402a70d27e09544a0e7',
    messagingSenderId: '674981416486',
    projectId: 'user-list-win',
    storageBucket: 'user-list-win.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4TDThy21I9BGpFZgYfjh7eK2hx5rJR1c',
    appId: '1:674981416486:ios:e252f57669b12b2e44a0e7',
    messagingSenderId: '674981416486',
    projectId: 'user-list-win',
    storageBucket: 'user-list-win.appspot.com',
    iosClientId: '674981416486-2vvrni5nl637oba6q4eo6k3qj288h2s4.apps.googleusercontent.com',
    iosBundleId: 'com.example.userListWin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4TDThy21I9BGpFZgYfjh7eK2hx5rJR1c',
    appId: '1:674981416486:ios:e252f57669b12b2e44a0e7',
    messagingSenderId: '674981416486',
    projectId: 'user-list-win',
    storageBucket: 'user-list-win.appspot.com',
    iosClientId: '674981416486-2vvrni5nl637oba6q4eo6k3qj288h2s4.apps.googleusercontent.com',
    iosBundleId: 'com.example.userListWin',
  );
}
